config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rest/urls.py
from django.urls import path
from . import views

app_name='rest'

urlpatterns = [

        path('create',views.Restcreate.as_view(),name='restform'),
        path('myrest',views.rest,name='myrest'),
        
        path('repcreate',views.RepCreate.as_view(),name='repcreate'),
        path('repupdate/<int:pk>',views.Repupdate.as_view(),name='repupdate'),

        path('rephome',views.rephome,name='rephome'),
        path('update/<int:pk>',views.Restupdate.as_view(),name='update'),



]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rest/models.py
from datetime import timedelta
from django.db import models
from report.models import Reportmodel,StationModel,DeviceModel
from django.contrib.auth import get_user_model as user_model
from django.db.models.aggregates import Avg
from django.db.models.fields import BLANK_CHOICE_DASH
from django.http import request
from jdatetime import datetime,date
import jdatetime
from jdatetime.jalali import JalaliToGregorian
from accounts.models import User
from django.utils import timezone
from django.db.models import F
from django.db.models.deletion import CASCADE
from jalali_date import datetime2jalali,date2jalali
from django_jalali.db import models as jmodels




User=user_model()


class Restmodel(models.Model):
    class Meta:
        verbose_name='مرحضی'
        verbose_name_plural='مرحضی'

    type_status=(('ساعتی','ساعتی'),('روزانه','روزانه'))
    accept_status=(('در دست بررسی','در دست بررسی'),
    ('تایید سرپرست','تایید سرپرست'),
    ('تایید ناظر','تایید ناظر'),
    ('تایید نشده','تایید نشده'))


    
    user=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,verbose_name='نام جایگزین')
    user1=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name='user',verbose_name='نام کاربری')
    date=jmodels.jDateField(verbose_name='تاریخ ثبت')
    time1=models.TimeField(null=True,verbose_name='شروع مرخصی')
    time2=models.TimeField(null=True,verbose_name='پایان مرخصی')
    dateexit=jmodels.jDateField(verbose_name='تاریخ ورود')
    type=models.CharField(max_length=20,default='h',choices=type_status,verbose_name='نوع مرخصی')
    accept=models.CharField(default='در دست بررسی',max_length=30,choices=accept_status,verbose_name='وضیعت')
    
    




    def __str__(self):
        
        return '{} {} {}'.format(self.user,self.user1,self.type)

    

    def persian_number(self):
        datetime2jalali=str(self.time1)
        
        number={
            '0':'۰',
            '1':'۱',
            '2':'۲',
            '3':'۳',
            '4':'۴',
            '5':'۵',
            '6':'۶',
            '7':'۷',
            '8':'۸',
            '9':'۹',
       }

        for i,j in number.items():
            datetime2jalali=datetime2jalali.replace(i,j)
           
        
        
        return datetime2jalali
    def persian_number1(self):
  
        time1str=str(self.time2)
        
        number={
            '0':'۰',
            '1':'۱',
            '2':'۲',
            '3':'۳',
            '4':'۴',
            '5':'۵',
            '6':'۶',
            '7':'۷',
            '8':'۸',
            '9':'۹',
       }

        for i,j in number.items():
            time1str=time1str.replace(i,j)
        
        
        return time1str   
    @property
    def timeavg(self):
        if (self.dateexit > self.date):
            a=(self.dateexit-self.date).days
       
        
            return '{} {}'.format(a,'روز')
        else:


            time=jdatetime.datetime.time(self.time1)
            time3=jdatetime.datetime.time(self.time2)
            td1 =jdatetime.date.today()
            timefinal =str(jdatetime.datetime.combine(td1,time3)-jdatetime.datetime.combine(td1,time))
                
        
            number={
                '0':'۰',
                '1':'۱',
                '2':'۲',
                '3':'۳',
                '4':'۴',
                '5':'۵',
                '6':'۶',
                '7':'۷',
                '8':'۸',
                '9':'۹',
                'd':'ر',
                'a':'و',
                'y':'ز',
        }

            for i,j in number.items():
                timefinal=timefinal.replace(i,j)
        
            
        return  timefinal


    def dayrest(self):
        a=(self.dateexit-self.date).days
       
        
        return '{} {}'.format(a,'روز')
    
        



class Repmodel(models.Model):
    class Meta:
        verbose_name=' سیستم قطعات معیوب'
        verbose_name_plural='سیستم قطعات معیوب'

    subj_status=(('قطعه تحویل مهندسی می باشد','قطعه تحویل مهندسی می باشد'),
    ('قطعه در انبار می باشد','قطعه در انبار می باشد'),
    ('در حال تست','در حال تست'),
    ('نصب شده','نصب شده'),)



    user=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,verbose_name='نام کاربری')
    dev_code=models.CharField(max_length=50,null=True,unique=True,verbose_name='کد اموال')
    dev_code1=models.CharField(max_length=50,null=True,verbose_name='کد انبار')
    date=jmodels.jDateTimeField(default= datetime.now().replace(microsecond=0),verbose_name='تاریخ ثبت')
    name=models.ForeignKey(DeviceModel,null=True,on_delete=models.SET_NULL,max_length=150,verbose_name='نام قطعه')
    station=models.ForeignKey(StationModel,null=True,on_delete=models.SET_NULL,max_length=50,verbose_name='نام ایستگاه')
    subj=models.CharField(max_length=500,choices=subj_status,verbose_name='توضیحات')

   


    def time2time(self):        
            
        datetime2jalali=str(self.date.strftime("%Y-%m-%d %X"))
                
        number={
            '0':'۰',
            '1':'۱',
            '2':'۲',
            '3':'۳',
            '4':'۴',
            '5':'۵',
            '6':'۶',
            '7':'۷',
            '8':'۸',
            '9':'۹',
       }

        for i,j in number.items():
            datetime2jalali=datetime2jalali.replace(i,j)
        
            
        return datetime2jalali

rest/views.py
from django.contrib.admin.widgets import AdminRadioSelect
from django.db.models import manager
from accounts.models import User as user3


from django.shortcuts import redirect, render
from django.shortcuts import HttpResponse
from jalali_date.fields import JalaliDateField, JalaliDateTimeField
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView,UpdateView
from django import forms
from .mixin import *
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from django.contrib.auth.models import AbstractBaseUser, UserManager 
from accounts.models import User

User=user_model()



# Create your views here.


class Restcreate(LoginRequiredMixin,Jalali2date,FormValid,FieldMixin,CreateView):
    model=Restmodel
    
    
    template_name='rest.html'
    
    
    def get_success_url(self):
        return reverse('rest:myrest')

    def get_form(self,form_class=None):
        
        form=super().get_form(form_class)
        if self.request.user.is_admin or self.request.user.is_nazer:

            user2=User.object.all()
            form.fields['user'].queryset =user2
            return form
        else:
            user2=User.object.filter(is_admin=False,is_nazer=False)
            form.fields['user'].queryset =user2
        
        return form
        
      
       
        

           

        
        
        
        

class RepCreate(LoginRequiredMixin,FormRepValid,FieldRepMixin,CreateView):
    model=Repmodel
    #fields='__all__'
    template_name='rep.html'
    
    def get_form(self,form_class=None):
        form=super().get_form(form_class)

        form.fields['date'].disabled=True
        return form
        
    
    def get_success_url(self):
        return reverse('rest:rephome')

class Repupdate(AccsesrepMixin,FieldRepMixin,UpdateView):
    model=Repmodel
    template_name="rep.html"

    def get_form(self,form_class=None):
        form=super().get_form(form_class)

        form.fields['date'].disabled=True
        return form
        

    def get_success_url(self):
        return reverse('rest:rephome')

class Restupdate(AccsesMixin,FieldMixin,UpdateView):
    model=Restmodel
   
    template_name='rest.html'

    def get_success_url(self):
        return reverse('rest:myrest')
@login_required
def rephome(request):
    form=Repmodel.objects.all().order_by('-date')
    return render (request,'rephome.html',{'form':form})

@login_required
def rest(request):

    if request.user.is_admin or request.user.is_nazer\
         or request.user.is_manager:
                
        form=Restmodel.objects.all().order_by('-time1')
        return render(request,'resthome.html',{'form':form})

    else:

        form=Restmodel.objects.filter(user1=request.user.id)
        return render(request,'resthome.html',{'form':form})

rest/templates/rep.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load jalali_tags %}



{% block titel %}
 سیستم قطعات معیوب
{% endblock titel %}


{% block main %}

<!-- OR -->
<!-- loading by form (if used AdminJalaliDateWidget) -->

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title mb-0 float-left">قطعات معیوب</h3>
     
    </div>

     

  
<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
      
      <div class="col-6">
        {% if request.user.is_admin or request.user.is_nazer %}
        {{form.user|as_crispy_field }}
        
        {% endif %}
        
        {{form.date|as_crispy_field }}
        {{form.subj|as_crispy_field}}

        
        
        
      </div>
      <div class='col-6'>
        {{form.name|as_crispy_field }}
        {{form.station|as_crispy_field }}

      </div>
     
          

      </div>
      <button type="submit" class='btn btn-success'>ارسال </button>   
    
        
   
       
      </div>
    
</form> 


{% endblock main %}

rest/templates/rephome.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block titel %}
قطعات معیوب
{% endblock titel %}



{% block main %}

<div class="col-12">
    <div class="card">
      
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover">
          <thead>
            <tr>
              
              <th>نام کاربر</th>
              <th>نام قطعه</th>
              <th>تاریخ ثبت</th>
              <th>نام ایستگاه </th>
              <th>توضیحات</th>
              
            </tr>
          </thead>
          <tbody>
            <tr>
              {% for reps in form  %}
              
                                       
              <td>{{reps.user.first_name}}  {{reps.user.last_name}}</td>
              {% if request.user.is_admin or request.user.is_nazer  %}
              <td><a href=" {% url 'rest:repupdate' reps.id %} " > {{reps.name}}</a></td>
              {%else%}
              <td>{{reps.name}}</td>
              {% endif %}
              
              <td>{{reps.time2time}}</td>
              <td>{{reps.station}}</td>
              <td><span class="badge badge-primary"> {{reps.subj}}</span></td>
             
            </tr>
            {% endfor %}

          </tbody>
        </table>
       
      </div>
      <!-- /.card-body -->
    </div>
    
  </div>
 
</div>

    

{% endblock main %}

rest/templates/rest.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block titel %}
 سیستم مرخصی
{% endblock titel %}


{% block main %}

<!-- OR -->
<!-- loading by form (if used AdminJalaliDateWidget) -->

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header"> 
        <h3 class="card-title mb-0 float-left">ارسال مرخصی</h3>
     
    </div>
   

  
<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
      
      <div class="col-6">
        
        {{form.user|as_crispy_field }}
        {{form.date|as_crispy_field }}


      </div>
      <div class='col-6'>
        {{form.type|as_crispy_field }}
        {{form.dateexit|as_crispy_field }}

      </div>
     
     
        <div class='col-6'>
        {{ form.time1|as_crispy_field }}
        {%if request.user.is_admin%}
        {{ form.accept|as_crispy_field }}
        
        {%elif request.user.is_manager%}
          <select name="accept" class="select form-control" id="id_accept">
            
            <option value="تایید سرپرست">تایید سرپرست</option>

            <option value="تایید نشده">تایید نشده</option>
          </select>

          {%elif request.user.is_nazer%}
          <select name="accept" class="select form-control" id="id_accept">
            
            <option value="تایید ناظر">تایید ناظر</option>

            <option value="تایید نشده">تایید نشده</option>
          </select>
          {%else%}
          <select name="accept" class="select form-control" id="id_accept">
            <option value="در دست بررسی" selected="">در دست بررسی</option>
          </select>
       
          {%endif%}

      
        </div>
       
       
        
      
        <div class='col-6'>
        {{ form.time2|as_crispy_field }}
        {% if request.user.is_admin  or request.user.is_nazer or request.user.is_manager  %}
        {{ form.user1|as_crispy_field }}
        {% endif %}
      
        </div>
        




      

      </div>
      <button type="submit" class='btn btn-success'>ارسال مرخصی</button>   
    
        
   
       
      </div>
    
</form> 


{{ form.media }}


{% endblock main %}

rest/templates/resthome.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block titel %}
 سیستم مرخصی
{% endblock titel %}



{% block main %}
  

<div class="col-12">
    <div class="card">
      
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover">
          <thead>
            <tr>
              
              <th>نام کاربر</th>
              <th>شروع مرخصی</th>
              <th>پایان مرخصی</th>
              <th>نام جایگزین</th>
              <th>میزان مرخصی</th>
              <th>نوع مرخصی</th>
              <th>تاریخ شروع مرخصی</th>
              <th>تاریخ خاتمه مرخصی</th>
              <th>وضیعت</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              {% for rests in form  %}
              
                                       
              <td> {% if rests.accept in  'در دست بررسی' and request.user.is_manager  %}

                <a href="{% url 'rest:update' rests.pk %}"> {{rests.user1.first_name}} {{rests.user1.last_name}}</a>

                <td>{% elif rests.accept in  'تایید سرپرست' and request.user.is_nazer  %}
                  <a href="{% url 'rest:update' rests.pk %}"> {{rests.user1.first_name}} {{rests.user1.last_name}}</a>

                {%else%}
                {{rests.user1.first_name}} {{rests.user1.last_name}}
              {% endif %}</td>

              <td>{{rests.persian_number}} </td>
              <td>{{rests.persian_number1}}</td>
              <td>{{rests.user.first_name}}  {{rests.user.last_name}}</td>

              <td>{{rests.timeavg}}</td>
              <td>{{rests.type}}</td>
              <td>{{rests.date}}</td>
              <td>{{rests.dateexit}}</td>
             <td>
                  {% if 'در دست بررسی' in rests.accept %}
                  <span class='badge badge-secondary'> در حال بررسی</span>
                  {%elif 'تایید سرپرست' in rests.accept %}
                  <span class='badge badge-primary'> تایید سرپرست</span>

                  {%elif 'تایید ناظر' in rests.accept %}
                  <span class='badge badge-success'> تایید ناظر</span>
                  
                  {%else%}

                  <span class='badge badge-danger'> تایید نشده</span>
                  
                  {% endif %}



             </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>
       
      </div>
      <!-- /.card-body -->
    </div>
    
  </div>
 
</div>

    

{% endblock main %}