accounts/urls.py
from django.urls import path,include
from . import views
from .views import *

app_name='account'
urlpatterns = [
    path('logout',views.logout,name='logout'),
    path('login',views.login,name='login'),
    path('profile',Profile.as_view(),name='profile'),
    path('password_change/',views.PasswordChange,name='password_change'),
    path('rest/',views.RestPassword.as_view(),name='rest'),
    path('rest/done/',views.DonePassword.as_view(),name='done'),
    path('confrim/<uidb64>/<token>/',views.Passwordrestconfig.as_view(),name='Passwordrestconfig'),
    path('confrim/done',views.Complate.as_view(),name='comlate'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rest/urls.py
from django.urls import path
from . import views

app_name='rest'

urlpatterns = [

        path('create',views.Restcreate.as_view(),name='restform'),
        path('myrest',views.rest,name='myrest'),
        
        path('repcreate',views.RepCreate.as_view(),name='repcreate'),
        path('repupdate/<int:pk>',views.Repupdate.as_view(),name='repupdate'),

        path('rephome',views.rephome,name='rephome'),
        path('update/<int:pk>',views.Restupdate.as_view(),name='update'),



]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django_jalali.db import models as jmodels

class UserManager(BaseUserManager):

    def create_user(self,first_name,last_name,idcart,phone,email,address,shift,password,date):
             
        if not password:
            raise ValueError('plz password')        
    




        user=self.model(email=self.normalize_email(email),first_name=first_name,last_name=last_name,
        idcart=idcart,phone=phone,address=address,shift=shift,password=password)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,first_name,last_name,idcart,phone,email,address,shift,password,date):
        user=self.create_user(first_name,last_name,idcart,phone,email,address,shift,password,date)
        user.is_admin=True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    class Meta:
        verbose_name = 'وضیعت کاربری'
        verbose_name_plural='وضیعت کاربری'
    shift_status=((' A شیفت ',' A شیفت '),(' B شیفت ',' B شیفت '),
                (' C شیفت ',' C شیفت '),

    )
    first_name=models.CharField(max_length=100,verbose_name='نام')
    last_name=models.CharField(max_length=100,verbose_name='نام خانوادگی')
    idcart=models.CharField(max_length=10,unique=True,verbose_name='شماره ملی(شناسه کاربری)')
    phone=models.CharField(max_length=11,verbose_name='تلفن همراه')
    email=models.EmailField(blank=True,unique=True,verbose_name='ایمیل')
    address=models.CharField(max_length=250,verbose_name='آدرس')
    shift=models.CharField(max_length=10,choices=shift_status,blank=True,null=True,verbose_name='شیفت')
    date=jmodels.jDateField(null=True,verbose_name='تاریخ استخدام')
    
    
    is_active=models.BooleanField(default=True,verbose_name='کاربر عادی')
    is_admin=models.BooleanField(default=False,verbose_name='مدیر')
    is_authe=models.BooleanField(default=False,verbose_name='سرشیفت')
    is_manager=models.BooleanField(default=False,verbose_name='سرپرست')
    is_nazer=models.BooleanField(default=False,verbose_name='ناظر')
    
    USERNAME_FIELD='idcart'
    REQUIRED_FIELDS=['first_name','last_name','phone','email','address','shift','date']
    object=UserManager()

    def __str__(self):
        return (f'{self.first_name} {self.last_name}')


    def has_perm(self, perm,obj=None):
        return True
    
    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin  
    

        

accounts/forms.py
from django import forms
from django.db.models import fields
from django.forms.forms import Form
from django.forms.models import ModelForm
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib import messages



class UsercreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['first_name','last_name','idcart','phone','email','address','shift','date','password']

    def clean_password2(self):
        data=self.cleaned_data
        if data['password2'] and data['password1'] and data['password2'] !=data['password1']:
            raise forms.ValidationError('plz check password')
        return data['password2']


    def save(self,commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user    

class UserchangeForm(forms.ModelForm):
    password=ReadOnlyPasswordHashField

    class Meta:
        model=User
        fields=['first_name','last_name','idcart','phone','email','address','shift','date','password']

    def clean_password(self):
        return self.initial['password']

class Userloginform(forms.Form):
    idcart=forms.CharField()
    password=forms.CharField(label='رمز عبور',widget=forms.PasswordInput)


class Profileforms(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        user=kwargs.pop('user')
        
        super(Profileforms,self).__init__(*args,**kwargs)
        if not user.is_admin:
            self.fields['idcart'].disabled=True
            self.fields['phone'].disabled=True
            self.fields['shift'].disabled=True
            self.fields['date'].disabled=True
            self.fields['is_nazer'].disabled=True
            self.fields['is_authe'].disabled=True
            self.fields['is_manager'].disabled=True
            self.fields['is_active'].disabled=True
    class Meta:
        model=User
        fields='__all__'

accounts/views.py
from django.contrib.messages.api import success
from django.http import request
from django.shortcuts import render,redirect, resolve_url
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate,login as auth_login,logout as django_logout
from django.contrib import messages
from report.decorators import unauthanticate
from django.views.generic import CreateView,UpdateView

from django.contrib.auth.forms import PasswordChangeForm,PasswordResetForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib.auth import views as authviews



class RestPassword(authviews.PasswordResetView):
    template_name='restpasword.html'
    success_url=reverse_lazy('account:done')
    email_template_name='link.html'

class DonePassword(authviews.PasswordResetDoneView):
    template_name='donepassword.html'

class Passwordrestconfig(authviews.PasswordResetConfirmView):
    template_name='passwordrestconfig.html'
    success_url=reverse_lazy('account:comlate')

class Complate(authviews.PasswordResetCompleteView):
    template_name='complate.html'



@unauthanticate
def login(request):
    #if request.user.is_authenticated:
        #return redirect("account:home")

    
    #else:
        #form=Userloginform()
        if request.method=='POST':
            form=Userloginform(request.POST) 
            if form.is_valid():
                data=form.cleaned_data
                user=authenticate(request,idcart=data['idcart'],password=data['password'])
                if user is not None:
                    auth_login(request, user)
                    messages.success(request,'با موفقیت وارد شدید',extra_tags='success')
                    return redirect('net:listreport')
                else:
                    messages.success(request,'نام کاربری و پسورد شما اشتباه است',extra_tags='danger')

            
        else:
            form=Userloginform()
        
        return render(request,'login.html',{'form':form})




def logout(request):
    django_logout(request)
    messages.success(request,'با موفقیت خارج شدید',extra_tags='warning')
    return redirect('account:login')

class Profile(LoginRequiredMixin,UpdateView):
    model=User
    template_name='profile.html'
    form_class=Profileforms
    def get_object(self):
        return User.object.get(pk=self.request.user.pk)
    def get_form_kwargs(self):
        kwargs= super(Profile,self).get_form_kwargs()
        kwargs.update({
            'user':self.request.user
         } )
                

        return kwargs



def PasswordChange(request):
    if request.method == 'POST':
        form=PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success(request,'رمز عبور با موفیقت تغییر یافت','success')
            return redirect('account:profile')
        else:
            messages.error(request,'پسورد انتخابی صحیح نمی باشد','danger')
            redirect('account:password_change')

    else:

        form=PasswordChangeForm(request.user)

    return render(request,'pswchange.html',{'form':form})

    

accounts/templates/complate.html
{% extends "base.html" %}

{% block main%}
<p>ورود به سامانه </p>
{%endblock%}

accounts/templates/donepassword.html
{% extends "base.html"%}

{% block main %}

<p>cheack your Email Address</p>

{% endblock%}

accounts/templates/home.html
{% extends "base.html" %}

{% block titel%}صفحه اصلی{% endblock%}


{% block main %}
  


<div class="row">
    <div class="col-12">
      <div class="card">
        
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>شماره</th>
                <th>نام کاربر</th>
                <th>تاریخ</th>
                <th>شیفت</th>
                <th>وضیعت</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>183</td>
                <td>John Doe</td>
                <td>11-7-2014</td>
                <td><span class="tag tag-success">Approved</span></td>
                <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
              </tr>
              <tr>
                <td>219</td>
                <td>Alexander Pierce</td>
                <td>11-7-2014</td>
                <td><span class="tag tag-warning">Pending</span></td>
                <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
              </tr>
              <tr>
                <td>657</td>
                <td>Bob Doe</td>
                <td>11-7-2014</td>
                <td><span class="tag tag-primary">Approved</span></td>
                <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
              </tr>
              <tr>
                <td>175</td>
                <td>Mike Doe</td>
                <td>11-7-2014</td>
                <td><span class="tag tag-danger">Denied</span></td>
                <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


  {% endblock main %}

accounts/templates/link.html
 سلام  تغییر رمز عبور برای شما 
{{protocol}}://{{domain}}{% url 'account:Passwordrestconfig' uidb64=uid token=token %}

accounts/templates/login.html
 {% load static%}
 {% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>صفحه ورود</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{%static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'login/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'login/css/rtl.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class='erorr'>
			{% if messages %}
						<ul class="messages">
							{% for message in messages %}
							<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
						{% endif %}
		</div>
		<div class="container-login100">
					<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST"> {% csrf_token %}
					<span class="login100-form-title p-b-26 myfont">
						
						ورود به سامانه
					</span>
					<span class="login100-form-title p-b-48 myfont">
						<i class="zmdi zmdi-account"></i>
					</span>


					<div class="wrap-input100 validate-input myfont" data-validate = "123456789">
						{{form.idcart|add_class:'input100'}}
						<span class="focus-input100 myfont" data-placeholder="شماره ملی"></span>
					</div>

					<div class="wrap-input100 validate-input myfont" data-validate="Enter password">
						<span class="btn-show-pass myfont">
							<i class="zmdi zmdi-eye"></i>
						</span>
						{{form.password|add_class:'input100'}}
						<span class="focus-input100 myfont" data-placeholder="رمز عبور"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn myfont">
								ورود به سامانه
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
					<a href="{% url 'account:rest'%}"><span class="txt1 myfont">
							فراموشی رمز عبور
						</span>

					</a>	


						<a class="txt2" href="#">
						</a>
						
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{%static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{%static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'login/js/main.js' %}"></script>

</body>
</html>

accounts/templates/login4.html
{%load static%}
<!DOCTYPE html>

<html lang="en">
<head>
	<title>ورود به سامانه</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{%static 'reg/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{%static 'reg/css/rtl.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/bootstrap/css/bootstrap.min.css' %}">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'reg/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'reg/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'reg/css/main.css' %}">

<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-50 p-b-90">
				<form class="login100-form validate-form flex-sb flex-w" method="POST" >{% csrf_token %}
					<span class="login100-form-title p-b-51 myfont">
						  ورود به سامانه
					</span>
							
					
					<div class="wrap-input100 validate-input m-b-16 " data-validate = "Username is required">
						{{form.idcart}}
						
						<input class="input100 myfont" type="text" name="username" placeholder="کلمه کاربری">
						<span class="nput100 myfont">{{form.password}}</span>
					</div>
					
					
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
						<input class="input100 myfont" type="password" name="pass" placeholder="رمز عبور">
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-t-3 p-b-24">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100 myfont" for="ckb1">
								ذخیره
							</label>
						</div>

						<div>
							<a href="#" class="txt1 myfont">
								فراموشی رمز عبور
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn myfont" type="submit">
							ورود به سامانه
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{%static 'reg/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{%static 'reg/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'reg/js/main.js' %}"></script>

</body>
</html>

accounts/templates/passwordrestconfig.html
{% extends "base.html" %}

% block main %}
<form method="post" enctype="application/x-www-form-urlencoded">
    {% if validlink %}
      
    
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
        
        {{form.as_p}}
              
    </div>

    <div class="col-6">
       
      
    </div>

    </form>
    {% endif %}
      <button type="submit" class='btn btn-success'>تغییر رمز عبور </button> 

accounts/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{{% block titel %}
  پروفایل کاربری
{% endblock titel %}}

{% block main %}

<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
      
      <div class="col-6">

        
        {{form.first_name|as_crispy_field }}
      </div>
      <div class='col-6'>
        {{form.last_name|as_crispy_field }}
      </div>
        
      <div class='col-6'>
        {{form.idcart|as_crispy_field }}
    </div>

    <div class='col-6'>
        {{form.phone|as_crispy_field }}
        
    </div>

    <div class='col-6'>
        {{form.address|as_crispy_field }}
        {{form.shift|as_crispy_field }}


    </div>

    <div class='col-6'>
        {{form.date|as_crispy_field }}
       

    </div>
    {% if request.user.is_nazer or request.user.is_admin %}
    {{form.is_nazer|as_crispy_field }}
    {% elif request.user.is_manager or request.user.is_admin %}
    {{form.is_manager|as_crispy_field}}
    {% elif request.user.is_authe or request.user.is_admin %}
    {{form.is_authe|as_crispy_field}}
    {%else%}
    

    {{form.is_active|as_crispy_field}}

    {% endif %}
    </div>
    <button type="submit" class='btn btn-success'>ویرایش مشخصات </button>   
    <a href="{% url 'account:password_change' %}"><button type='button' class='btn btn-danger'>  تغییر رمز عبور</button>  </a>
    
        
   
       
      
</form> 
  
{% endblock main %}

accounts/templates/pswchange.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block title%} تغییر رمز عبور{%endblock%}

{%block titel%} تغییر رمز عبور{%endblock%}


{% block main %}
<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
        
        {{ form.old_password|as_crispy_field }}
              
    </div>

    <div class="col-6">
       
      
    </div>

    <div class="col-6">
        {{form.new_password2|as_crispy_field }}
        {{form.new_password1|as_crispy_field }} 
       </div>

      </div>
      <button type="submit" class='btn btn-success'>تغییر رمز عبور </button>   
    
        
   
       
      </div>
    
</form> 

{% endblock main %}

accounts/templates/restpasword.html
{% extends "base.html" %}

{% block main %}
<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
        
        {{form}}
        </div>
    </div>

      <button type="submit" class='btn btn-success'>ارسال کلمه عبور</button>   
    </form>

      {% endblock %}