accounts/urls.py
from django.urls import path,include
from . import views
from .views import *

app_name='account'
urlpatterns = [
    path('logout',views.logout,name='logout'),
    path('login',views.login,name='login'),
    path('profile',Profile.as_view(),name='profile'),
    path('password_change/',views.PasswordChange,name='password_change'),
    path('rest/',views.RestPassword.as_view(),name='rest'),
    path('rest/done/',views.DonePassword.as_view(),name='done'),
    path('confrim/<uidb64>/<token>/',views.Passwordrestconfig.as_view(),name='Passwordrestconfig'),
    path('confrim/done',views.Complate.as_view(),name='comlate'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from .views import *

app_name='net'
urlpatterns = [

        path('listreport',listreport,name='listreport'),
        path('detailreport/<slug:slug>',Reportdeatail.as_view(),name='detail'),
        path('reportform/create',ReportCreate.as_view(),name='reportform'),
        path('myreport',myreport,name='myreport'),
        path('home',home,name='home'),
        path('reportform/update/<int:pk>',Reportupdate.as_view(),name='reportupdate'),

]

rest/urls.py
from django.urls import path
from . import views

app_name='rest'

urlpatterns = [

        path('create',views.Restcreate.as_view(),name='restform'),
        path('myrest',views.rest,name='myrest'),
        
        path('repcreate',views.RepCreate.as_view(),name='repcreate'),
        path('repupdate/<int:pk>',views.Repupdate.as_view(),name='repupdate'),

        path('rephome',views.rephome,name='rephome'),
        path('update/<int:pk>',views.Restupdate.as_view(),name='update'),



]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{%load static%}
{% load jalali_tags %}




<!DOCTYPE html>
<html>


<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title%}سامانه جامع نت{% endblock%}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href= " { % static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' % } ">
  <script src="{ % static 'admin/js/django_jalali.min.js' % }"></script>		
  <!-- Font Awesome -->
  <link rel="stylesheet" href= " {% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href= " {%static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">
  <!-- iCheck -->
  <link rel="stylesheet" href=" {%static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">}
  <!-- JQVMap -->
  <link rel="stylesheet" href=" {%static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href=" {%static 'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href=" {%static 'dist/css/rtl.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href=" {%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href=" {%static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href=" {%static 'plugins/summernote/summernote-bs4.css' %}">
  
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link href='https://css.gg/lock-unlock.css' rel='stylesheet'>
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href=" {%static 'dist/css/custom.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="" class="nav-link">صفحه اصلی</a>
      </li>
    </ul>
   

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="جستجو" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
      <!-- Messages Dropdown Menu -->
     
          <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{% url 'account:logout'%}">
          <i class="fas fa-sign-out-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
 {% include "sidebar.html" %}
 {% include "msg.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block titel %}صفحه اصلی
              
            {% endblock titel %}</h1>
          </div><!-- /.col -->
         
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <p><span class='badge badge-danger'> ساعت  {% now "H:i" %}</span></p>  
        {% block main %}
       
        {% endblock main %}
      
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    
    <strong> &copy; 2021  <a href=""> سامانه جامع نت </a>.</strong>
    
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 2.5
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->static
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{%static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->


<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- ChartJS -->
<script src="{%static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{%static 'plugins/sparklines/sparkline.js' %} "></script>
<!-- JQVMap -->
<script src="{%static 'plugins/jqvmap/jquery.vmap.min.js' %} "></script>
<script src="{%static 'plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{%static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{%static 'plugins/moment/moment.min.js' %} "></script>
<script src="{%static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{%static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %} "></script>
<!-- Summernote -->
<script src="{%static 'plugins/summernote/summernote-bs4.min.js' %} "></script>
<!-- overlayScrollbars -->
<script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %} "></script>
<!-- AdminLTE App -->
<script src="{%static 'dist/js/adminlte.js' %} "></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{%static 'dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{%static 'dist/js/demo.js' %}"></script>
</body>
</html>

templates/msg.html
{%load static%}

<head>
  <link rel="stylesheet" href=" {%static 'dist/css/rtl.css' %}">
</head>
{%if messages %}

{%for msg in messages%}
{%if msg.tags%}
<div class="alert alert-{{msg.tags}}" role="alert" style="padding: .05rem 25rem;">
    {%endif%}
{{msg}}
  </div>
{%endfor%}
{%endif%}

templates/sidebar.html
{%load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{%static 'dist/img/AdminLTELogo.png'%}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">سامانه جامع نت </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{%static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{user.first_name}} {{user.last_name}}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open ">
            <a href="#" class="nav-link active">
              <i class="nav-icon fa fa-file"></i>
              <p>
                پنل کاربری
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
         
        
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'net:reportform' %}" class="nav-link {% if request.resolver_match.url_name == 'reportform' %}active {%endif%}">
                  <i class="fa fa-edit nav-icon"></i>
                  <p>افزودن گزارش</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'net:listreport'%}" class="nav-link {% if request.resolver_match.url_name == 'listreport' %}active {%endif%}">
                  <i class="fa fa-list nav-icon"></i>
                  <p>لیست گزارش ها</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'net:myreport' %}" class="nav-link {% if request.resolver_match.url_name == 'myreport' %}active {%endif%}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>گزارش های شما</p>
                </a>
              </li>
          
          <li class="nav-item">
            <a href="{%url 'rest:restform'%}" class="nav-link {% if request.resolver_match.url_name == 'restform' %}active {%endif%}">
              <i class="fa fa-edit nav-icon"></i>
              <p>ارسال مرحضی</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{%url 'rest:myrest'%}" class="nav-link {% if request.resolver_match.url_name == 'myrest' %}active {%endif%}">
              <i class="fa fa-list nav-icon"></i>
              <p>مرحضی های من</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'rest:repcreate' %}" class="nav-link {% if request.resolver_match.url_name == 'repcreate' %}active {%endif%}">
              <i class="nav-icon fas fa fa-wrench"></i>
              <p>
                  قطعات معیوب
                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{%url 'rest:rephome'%}" class="nav-link {% if request.resolver_match.url_name == 'rephome' %}active {%endif%}">
              <i class="fa fa-list nav-icon"></i>
              <p>لیست قطعات</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'account:profile' %}" class="nav-link {% if request.resolver_match.url_name == 'profile' %}active {%endif%}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                پروفایل
                
              </p>
            </a>
          </li>


          
        </ul>

        
      </nav>
    
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>