config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from .views import *

app_name='net'
urlpatterns = [

        path('listreport',listreport,name='listreport'),
        path('detailreport/<slug:slug>',Reportdeatail.as_view(),name='detail'),
        path('reportform/create',ReportCreate.as_view(),name='reportform'),
        path('myreport',myreport,name='myreport'),
        path('home',home,name='home'),
        path('reportform/update/<int:pk>',Reportupdate.as_view(),name='reportupdate'),

]

rest/urls.py
from django.urls import path
from . import views

app_name='rest'

urlpatterns = [

        path('create',views.Restcreate.as_view(),name='restform'),
        path('myrest',views.rest,name='myrest'),
        
        path('repcreate',views.RepCreate.as_view(),name='repcreate'),
        path('repupdate/<int:pk>',views.Repupdate.as_view(),name='repupdate'),

        path('rephome',views.rephome,name='rephome'),
        path('update/<int:pk>',views.Restupdate.as_view(),name='update'),



]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls',namespace='account')),
    path('net/',include('report.urls',namespace='net')),
    path('rest/',include('rest.urls',namespace='rest')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/models.py
from datetime import date, datetime, time,timedelta
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.utils import timezone
from django.contrib.auth import get_user_model as user_model
from accounts.models import User
from django.db.models.fields import CharField
from django.urls import reverse
from jalali_date import datetime2jalali,date2jalali
from django.utils.text import slugify


import jdatetime
from django.db import models
from django_jalali.db import models as jmodels


from django.db.models import CharField, Model









User=user_model()



class DeviceModel(models.Model):
    class Meta:
        verbose_name = 'نام تجهیز'
        verbose_name_plural = 'نام تجهیز'
        ordering=['position']
    device_name = models.ForeignKey('self',null=True,blank=True,on_delete=models.SET_NULL,max_length=75,verbose_name='نام بخش',related_name='device')

    name=models.CharField(max_length=250, verbose_name='نام')
    slug=models.SlugField(max_length=50,unique=True,verbose_name='آدرس')
    status=models.BooleanField(default=True,verbose_name='نمایش ')
    position=models.IntegerField(default=None,verbose_name='موقیعت',)

    def __str__(self):
        return self.name

class StationModel(models.Model):
    class Meta:
        verbose_name = 'نام ایستگاه و مکان های مترو'
        verbose_name_plural = 'نام ایستگاه و مکان های مترو'
    mastername = models.ForeignKey('self',default=None,blank=True,null=True,on_delete=models.SET_NULL,related_name='name',verbose_name='زیر دسته')
    
    titel=models.CharField(max_length=50,verbose_name='عنوان')
    slug=models.SlugField(max_length=50,unique=True,verbose_name='آدرس')
    status=models.BooleanField(default=True,verbose_name='نمایش ')
    position=models.IntegerField(default=None,verbose_name='موقیعت',)



    def __str__(self):
        
        return '{}'.format(self.titel)
       
       


class Informationmodel(models.Model):
    class Meta:
        verbose_name='اطلاعات'
        verbose_name_plural='اطلاعات'
        ordering=['position']

    title=models.CharField(max_length=100,verbose_name='عنوان')
    slug=models.CharField(max_length=100,unique=True)
    status=models.BooleanField(default=True,verbose_name='نمایش')
    position=models.IntegerField(verbose_name='موقیعت')

    def __str__(self) -> str:
        return self.title



class Reportmodel(models.Model):
    class Meta:
        verbose_name='گزارش'
        verbose_name_plural='گزارش'
       
    acepet_status=(('تایید نشده','تایید نشده'), 
                    ('تایید سر شیفت','تایید سر شیفت'),
                    ('تایید نهایی','تایید نهایی'),
    
    )

    shift_status=(('شیفت A','شیفت A'),
    ('شیفت B','شیفت B'),
    ('شیفت C','شیفت C'),)

   
    subject=models.ForeignKey('StationModel',max_length=100,on_delete=models.CASCADE,verbose_name='مکان',related_name='cat')
    categ=models.ManyToManyField(Informationmodel,verbose_name='دسته بندیُ',related_name='info')
    device=models.ForeignKey('Devicemodel',on_delete=models.SET_NULL,null=True,verbose_name='نام تجهیز')
    report=models.CharField(max_length=550,verbose_name='شرح خرابی')
    date=jmodels.jDateTimeField(default=jdatetime.datetime.now,verbose_name='تاریخ ثبت',)
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='نام کاربری')
    shift=models.CharField(max_length=50,choices=shift_status,verbose_name='شیفت',null=True)
    acepet=models.CharField(max_length=30,choices=acepet_status,default='تایید نشده',verbose_name='وضیعت')
    slug=models.SlugField(unique=True,verbose_name='آدرس گزارش',blank=True)
    numbercmms=models.CharField(null=True,default='ICT-',max_length=50,verbose_name='شماره دستور کار')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.date)
        super().save(*args, **kwargs)

    def __str__(self):

        return "{} {} {} {} ".format(self.subject,self.date,self.user,self.shift)
    
    def get_absolute_url(self):
        return reverse("net:listreport")
    
    def get_absolute_url1(self):
        return reverse('net:detail',args=[self.slug])

  


    def __str__(self):
        return '{} {}'.format(self.subject, self.user)

    
    
    
    def persian_number(self):
        
        datetime2jalali=str(self.date.strftime("%Y-%m-%d %X"))
        
        
        number={
            '0':'۰',
            '1':'۱',
            '2':'۲',
            '3':'۳',
            '4':'۴',
            '5':'۵',
            '6':'۶',
            '7':'۷',
            '8':'۸',
            '9':'۹',
       }

        for i,j in number.items():
            datetime2jalali=datetime2jalali.replace(i,j)
        
            
        return datetime2jalali

    def timejalali(self):
        time=jdatetime.datetime(self.date)

        return time

report/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import fields, widgets
from django.http import request
from .models import *
from .models import User
from django.contrib.auth import get_user_model as user_model



User=user_model()


class Reportform(forms.ModelForm):
    class Meta:
        model=Reportmodel

       
        fields=['subject','categ','slug','date','report','shift','user','acepet']
        
    
    

report/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404
from .models import *
from accounts.mixin import *
from django.contrib.auth import authenticate,login
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from django.core.paginator import Paginator
from django.views.generic import CreateView,UpdateView,DetailView
from .decorators import mix, unauthanticate
from django.contrib.auth.decorators import login_required
from .forms import Reportform
from .forms import Informationmodel
from django.forms import *
#
@login_required
def listreport(request):
    #if request.user is authenticate:
        
    #print(request.user.is_authe)
        report=Reportmodel.objects.filter(categ=1).order_by('-date')
        paginator=Paginator(report,10)   
        pagenum=request.GET.get('page')
        page_obj=paginator.get_page(pagenum)
        context={'report':page_obj,'pagenum':pagenum}
    

        return render(request,'listreport.html',context)





#def detailreport(request,slug):
    
 #   form=Reportmodel.objects.get(slug=slug)
    
  #  return render(request,'deatil.html',{'form':form})
@login_required
def myreport(request):
    
    if request.user.is_admin or request.user.is_authe or request.user.is_nazer:
        myreport=Reportmodel.objects.all().order_by('-date')
        
        contax={'myreport':myreport}
        return render(request,'myreport.html',contax)

    else:
        myreport=Reportmodel.objects.filter(user=request.user.id)
        return render(request,'myreport.html',{'myreport':myreport})
@login_required
def home(request):
    
    context={'categ':Reportmodel.objects.filter(categ=1).order_by('-date')}


    return render(request,'home.html',context)

    
class Reportdeatail(DetailView):
    template_name='detailreport.html'
    def get_object(self):
        slug=self.kwargs.get('slug')
        return get_object_or_404(Reportmodel.objects.all(),slug=slug)

class ReportCreate(LoginRequiredMixin,FieldMixin,FormValidMixin,CreateView):
    model=Reportmodel
   #fields=['subject','categ','slug','date','report','shift','user','acepet']
    template_name='reportform.html'
    
    def get_form(self, form_class=None):
        form = super().get_form( form_class)
        
        form.fields['date'].disabled=True
        
        return form    


class Reportupdate(FieldUpdateMixin,FieldMixin,UpdateView):
    model=Reportmodel
   
    template_name='reportform.html'

report/templates/deatil.html
{% extends "base.html" %}


{% block main %}

<div class="card" style="background-color: rgb(120, 220, 238);">
    <div class="card-header">
      <h3 class="card-title"></h3>{{form.subject}}
      <span></span>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">
        <p>{{form.report|safe}}</p>
       
        
    </div>
    <!-- /.card-body -->
    <div class="card-footer " >
      <ul class="list-group list-group-flush" style="background-color: rgb(221, 220, 235);" >
         شیفت:{{form.shift}}
         تاریخ ثبت : {{form.persian_number}}
        
         
         
    
      
    </div>
    
    <!-- /.card-footer-->
  </div>



  
  
  
{% endblock main %}

report/templates/detailreport.html
{% extends "base.html" %}


{% block main %}

<div class="card" style="background-color: rgb(120, 220, 238);">
    <div class="card-header">
      <h3 class="card-title"></h3>{{object.subject}}
      <span></span>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i></button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i></button>
      </div>
    </div>
    <div class="card-body">
        <p>{{object.report|safe}}</p>
       
        
    </div>
    <!-- /.card-body -->
    <div class="card-footer " >
      <ul class="list-group list-group-flush" style="background-color: rgb(221, 220, 235);" >
         شیفت:{{object.shift}}
         تاریخ ثبت : {{object.persian_number}}
        
         
         
    
      
    </div>
    
    <!-- /.card-footer-->
  </div>



  
  
  
{% endblock main %}

report/templates/home.html
{% extends "base.html" %}

{% block title%}اطلاعیه{% endblock%}

{% block titel %}
  اخبار و اطلاعیه
{% endblock titel %}


{% block main %}
  


<div class="row">
    <div class="col-12">
      <div class="card">
        
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> شماره گزارش</th>
                <th>موضوع</th>
                <th>نام کاربر</th>
                <th>تاریخ</th>
                <th>شیفت</th>
                <th>وضیعت</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for info in categ  %}
    
                  
                
                <td>{{info.id}}</td>
                <td>  <a href="{{info.get_absolute_url1}}">{{info.subject}}</a></td>
                <td>{{info.user.first_name}} {{info.user.last_name}}</td>
                <td>{{info.persian_number}}</td>
                <td>{{info.shift}}</td>
                
                <td>
                 

              

                </td>
              </tr>

                <!-- Modal content -->



              {% endfor %}
              
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>

  
  
  {% endblock main %}

report/templates/listreport.html
{% extends "base.html" %}



{% block titel%}گزارشات{% endblock%}


{% block main %}
  


<div class="row">
    <div class="col-12">
      <div class="card">
        
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> شماره گزارش</th>
                <th>موضوع</th>
                <th>نام کاربر</th>
                <th>تاریخ</th>
                <th>شیفت</th>
                <th>وضیعت</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for reports in report  %}
    
                  
                
                <td>{{reports.id}}</td>
                <td>  <a href="{{reports.get_absolute_url1}}">{{reports.subject}}</a></td>
                <td>{{reports.user.first_name}} {{reports.user.last_name}}</td>
                <td>{{reports.persian_number}}</td>
                <td>{{reports.shift}}</td>
                <td>
                  {% if 'تایید نشده'  in reports.acepet%}
                    <span class='badge badge-danger'> تایید نشده</span>
                  {%elif 'تایید سر شیفت' in reports.acepet%}
                  <span class='badge badge-warning'>تایید سر شیفت</span>
                  {%else%}
                  <span class='badge badge-success'>تایید نهایی</span>

                  {% endif %}

                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>

  </div>



<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if report.has_previous %}

    <li class="page-item"><a class="page-link" href="?page={{report.previous_page_number}}">صفحه قبلی</a></li>

    <li class="page-item"><a class="page-link" href="?page={{report.previous_page_number}}">{{report.previous_page_number}}</a></li>

   

  {% endif %}
   

  <li class="page-item {% if pagenum == pagenum %} active  {% endif %}">

    <a class="page-link" href="?page{{report.page}}">{{report.number}}</a>
  </li>
  
  {% if report.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{report.next_page_number}}">{{report.next_page_number}}</a></li>
  <li class="page-item"><a class="page-link" href="?page={{report.next_page_number}}">صفحه بعد</a></li>

</ul>


{% endif %}





</nav>

  {% endblock main %}
  <li class="page-item"><a class="page-link" href="#">صفحه قبل</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>

report/templates/myreport.html
{% extends "base.html" %}

{% block titel %}
  گزارش های من
{% endblock titel %}


{%block main%}
<div class="row">
    <div class="col-12">
      <div class="card">
        
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> شماره گزارش</th>
                <th>نام کاربر</th>
                <th>تاریخ</th>
                <th>شیفت</th>
                <th>وضیعت</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for reports in myreport  %}
                
                {% if reports.acepet in 'تایید نشده' or request.user.is_admin or request.user.is_nazer  %}
                <td><a href="{% url 'net:reportupdate' reports.pk %}"  > {{reports.subject}}</a>  </td>
              {%else%}
                  
                <td>{{reports.subject}}  </td>
                {% endif %}
                <td>{{reports.id}}  </td>

                <td>{{reports.user.first_name}} {{reports.user.last_name}}</td>
                <td>{{reports.persian_number}}</td>
                <td>{{reports.shift}}</td>
                <td>
                  {% if 'تایید نشده'  in reports.acepet%}
                    <span class='badge badge-danger'> تایید نشده</span>
                  {%elif 'تایید سر شیفت' in reports.acepet%}
                  <span class='badge badge-warning'>تایید سر شیفت</span>
                  {%else%}
                  <span class='badge badge-success'>تایید نهایی</span>

                  {% endif %}

                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>

  {%endblock%}

report/templates/reportform.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load widget_tweaks %}




{% block titel %}
 ارسال گزارش
{% endblock titel %}


{%block main%}



<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title mb-0 float-left">ارسال گزارش</h3>
      </div>
    
  
<form method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="row">
      <div class="col-6">
   

        {{ form.subject|as_crispy_field }}
        {{form.numbercmms|as_crispy_field }}
        
        {{form.device|as_crispy_field }}
        {{ form.shift|as_crispy_field }}
      
       
        
      </div>
       
      <div class="col-6">
        {{form.date|as_crispy_field}}
        {% if request.user.is_admin   %}
        {{form.slug|as_crispy_field}}
        {% endif %}
        {{form.report|as_crispy_field}}
        

        {% if user.is_admin %}  
        {{ form.acepet|as_crispy_field }}
        
       
        {%elif user.is_nazer %}
        <label for="id_acepet">وضیعت*</label>
        <select name="acepet" class="select form-control" id="id_acepet" >
         <option value="تایید نشده" selected="">تایید نشده</option>
     
         
       
         <option value="تایید نهایی">تایید نهایی</option>
       
       </select>
       
       
         {%elif user.is_authe or user.is_manager %}
         <label for="id_acepet">وضیعت*</label>
         <select  name="acepet" class="select form-control" id="id_acepet" >
           
           <option value="تایید سر شیفت">تایید سر شیفت</option>
        
           </select>
       
           {%else%}    
       
      
       <select name="acepet" class="select form-control" id="id_acepet">
       <option value="تایید نشده" selected="">تایید نشده</option>
       
       
       </select>
    
      {% endif %}
       
        
      </div>
      
      
    <div class="col-6">
      

        {% if user.is_admin  %} 
        {{ form.user|as_crispy_field }}
        {% endif %}   
    </div>
    <div class="col-6">
      
         {% if user.is_admin   %}
         {{ form.categ|as_crispy_field }}
        {%endif%}
                

    </div>
        
  </div>
          
<button type="submit" class='btn btn-success'>ارسال گزارش</button>
</form>

{%endblock %}

report/templates/reportupdate.html
{% extends "base.html" %}

{% block titel%}گزارشات{% endblock%}


{% block main %}
  


<div class="row">
    <div class="col-12">
      <div class="card">
        
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> شماره گزارش</th>
                <th>موضوع</th>
                <th>نام کاربر</th>
                <th>تاریخ</th>
                <th>شیفت</th>
                <th>وضیعت</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for reports in report  %}
    
                  
                
                <td>{{reports.id}}</td>
                <td>  <a href="{% url report:updatereport' report.pk %}">{{reports.subject}}</a></td>
                <td>{{reports.user.first_name}} {{reports.user.last_name}}</td>
                <td>{{reports.persian_number}}</td>
                <td>{{reports.shift}}</td>
                <td>
                  {% if 'تایید نشده'  in reports.acepet%}
                    <span class='badge badge-danger'> تایید نشده</span>
                  {%elif 'تایید سر شیفت' in reports.acepet%}
                  <span class='badge badge-warning'>تایید سر شیفت</span>
                  {%else%}
                  <span class='badge badge-success'>تایید نهایی</span>

                  {% endif %}

                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>


  {% endblock main %}